export const productList = [
  {
    id: '1',
    name: 'Jersey - short sleeves',
    color: 'light blue',
    price: '20',
    currency: '€',
    description:
      'breathable fabric, soft-touch, moisture resistance, quick dry, 100% polyester, unisex cut only',
    imgFront: '/jerseyBlueShortFront.jpg',
    imgBack: '/jerseyBlueShortBack.jpg',
    sizes: ['S', 'M', 'L', 'XL'],
  },
  {
    id: '2',
    name: 'Jersey - long sleeves',
    color: 'light blue',
    price: '22',
    currency: '€',
    description:
      'breathable fabric, soft-touch, moisture resistance, quick dry, 100% polyester, unisex cut only',
    imgFront: '/jerseyBlueLongFront.jpg',
    sizes: ['S', 'M', 'L', 'XL'],
  },
  {
    id: '3',
    name: 'Hoodie',
    color: 'navy blue',
    price: '25',
    currency: '€',
    description:
      'Heavyweight three fly fleece cotton rich fabric, soften handle, double layer hood, unisex cut only',
    imgFront: '/hoodieBlueFront.jpg',
    imgBack: '/hoodieBlueBack.jpg',
    sizes: ['S', 'M', 'L', 'XL'],
  },
  {
    id: '4',
    name: 'Hoodie',
    color: 'light grey',
    price: '25',
    currency: '€',
    description:
      'Heavyweight three fly fleece cotton rich fabric, soften handle, double layer hood, unisex cut only',
    imgFront: '/hoodieGreyFront.jpg',
    imgBack: '/hoodieGreyBack.jpg',
    sizes: ['S', 'M', 'L', 'XL'],
  },
  {
    id: '5',
    name: 'Zipper Hoodie',
    color: 'light grey',
    price: '25',
    currency: '€',
    description:
      'Heavyweight three fly fleece cotton rich fabric, soften handle, double layer hood, unisex cut only',
    imgFront: '/hoodieZipperGreyFront.jpg',
    imgBack: '/hoodieGreyBack.jpg',
    sizes: ['S', 'M', 'L', 'XL'],
  },
  {
    id: '6',
    name: 'Softshell Jacket',
    color: 'navy blue',
    price: '30',
    currency: '€',
    description:
      '100% polyester bonded fabric, water repellent, wind proof, thermal fabric, resistant to mechanical damage, durable, unisex cut only',
    imgFront: '/softshellFront.jpg',
    imgBack: 'softshellBack.jpg',
    sizes: ['S', 'M', 'L', 'XL'],
  },
  {
    id: '7',
    name: 'Gym bag',
    color: 'navy blue',
    price: '15',
    currency: '€',
    description: '100% cotton fabric, durable',
    imgFront: '/gymbag.PNG',
  },
  {
    id: '8',
    name: 'Cap',
    color: 'navy blue',
    price: '10',
    currency: '€',
    description:
      '100% chino cotton twill, single size, adjustable strap with hook and pile',
    imgFront: '/snapback.PNG',
  },
  {
    id: '9',
    name: 'Headband',
    color: 'double sided - green white',
    price: '6',
    currency: '€',
    description:
      '100% polyester, double-sided, breathable fabric, quick dry, single size',
    imgFront: '/headband.jpg',
  },
];
