-- Create table
CREATE TABLE products (id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, product_name varchar(40) NOT NULL, color varchar(40) NOT NULL, price varchar(5) NOT NULL, currency varchar(1) NOT NULL, product_description varchar(250) NOT NULL, cut varchar(40) NOT NULL, img_Front varchar(250), img_Back varchar(250), sizes text []);

-- Insert information into table
INSERT INTO products (product_name, color, price, currency, product_description, cut, img_Front, img_Back, sizes)
  VALUES
  ('Jersey - short sleeves', 'Light blue', '20', '€', 'Breathable fabric, soft-touch, moisture resistance, quick dry, 100% polyester', 'Unisex cut only', '/jerseyBlueShortFront.jpg', '/jerseyBlueShortBack.jpg', ['S', 'M', 'L', 'XL']),
  ('Jersey - long sleeves', 'Light blue', '22', '€', 'Breathable fabric, soft-touch, moisture resistance, quick dry, 100% polyester', 'Unisex cut only', '/jerseyBlueLongFront.jpg', 'none', ['S', 'M', 'L', 'XL']),
  ('Hoodie', 'Navy blue','25', '€', 'Heavyweight three fly fleece cotton rich fabric, soften handle, double layer hood', 'Unisex cut only', '/hoodieBlueFront.jpg', '/hoodieBlueBack.jpg', ['S', 'M', 'L', 'XL']),
  ('Hoodie', 'Light grey', '25', '€', 'Heavyweight three fly fleece cotton rich fabric, soften handle, double layer hood', 'Unisex cut only', '/hoodieGreyFront.jpg', '/hoodieGreyBack.jpg',['S', 'M', 'L', 'XL']),
  ('Zipper Hoodie', 'Light grey', '25', '€',
    'Heavyweight three fly fleece cotton rich fabric, soften handle, double layer hood','Unisex cut only', '/hoodieZipperGreyFront.jpg', '/hoodieGreyBack.jpg',['S', 'M', 'L', 'XL']),
  ('Softshell Jacket', 'Navy blue', '30', '€', '100% polyester bonded fabric, water repellent, wind proof, thermal fabric, resistant to mechanical damage, durable', 'Unisex cut only', '/softshellFront.jpg', '/softshellBack.jpg', ['S', 'M', 'L', 'XL']),
  ('Gym bag', 'Navy blue', '15', '€', '100% cotton fabric, durable', 'Unisex cut only', '/gymbag.PNG', 'none', []),
  ('Cap', 'Navy blue', '10', '€', '100% chino cotton twill, single size, adjustable strap with hook and pile', 'Unisex cut only', '/snapback.PNG','none', []),
  ('Headband', 'double sided - green white', '6', '€', '100% polyester, double-sided, breathable fabric, quick dry, single size', 'Unisex cut only', '/headband.jpg', 'none', []);
